### ISSUE TITLE
Autocompletion problem in Rolemethods

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/haxedci#3]
In display mode, there is some problem with displaying all roleMethods. 

All methods in a role are transformed to a field on the class called `${role.name}__${field.name}`, but autocompletion stops at the method where the display expression is.

A solution is to save the current structure to disk, and let autocompletion read and display that instead, but I'd like to be sure I'm not missing anything before doing that.

@back2dos do you have some clever idea how to solve this?

```haxe
class MyContext implements dci.Context {
    // ... partial code...
    @role var source : {
        function decreaseBalance(a : Int) : Void;

        function addSource() : Void {
            source.| // withdraw is not displayed here, because it's below addSource.
        }

        function withdraw() {
            self.decreaseBalance(Std.int(amount / 2));
            destination.deposit();
        }
    }
}
```

**Comment by back2dos** [comment]
It's probably silly, but have you tried reordering the fields within the macro?

**Comment by ciscoheat** [comment]
Putting the field containing the EDisplay last? That is surely worth a try. :)

**Comment by back2dos** [comment]
So, any luck with that? ^^

**Comment by ciscoheat** [comment]
I hit some obstacles, but I'll be back later!

**Comment by ciscoheat** [comment]
Ok, I tried reordering the fields, but unfortunately it doesn't work. The `withdraw` field doesn't even exist in the build fields in display mode, actually.

**Comment by back2dos** [comment]
Phew. I suppose in that case the best you can do is store the structure during ordinary builds and merge it with what you find in display mode so you have a relatively good chance to get all current fields. 

Other than that I guess it'd be best to ask the compiler team about this particular display shortcut. Technically, it's forbidden in the standard language to put expression where you use them. So the behavior you're struggling with is really just unspecified and could therefore be bent in your favor. After all, display mode does look ahead upto a certain point: http://try.haxe.org/#1085f

**Comment by ciscoheat** [comment]
Yeah, I was hoping to avoid storing the structure, but it seems to be either that or getting it supported. I've noticed the same as in the example, outside the anonymous structure autocompletion works, but inside it stops as soon as it finds the function to autocomplete.

For now it'll do, and I'll talk to the compiler team. Thanks for your help. :)
